In [188]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [189]:
df1 = pd.read_csv('./data/raw/ai_fat_wave3_pt1.csv')
df2 = pd.read_csv('./data/raw/ai_fat_wave3_pt2.csv')

# add a column indicating the part
df1['part'] = 'part_1'
df2['part'] = 'part_2'

In [190]:
df_demographics1 = pd.read_csv('./data/raw/prolific_demographic_export_68e4ce20a1b531e5b6bfaf1b.csv') 
df_demographics2 = pd.read_csv('./data/raw/prolific_demographic_export_68e4cebf0dfea69a27122b30.csv')

In [191]:
# combine the two dataframes
df = pd.concat([df1, df2], ignore_index=True)
df_demographics = pd.concat([df_demographics1, df_demographics2], ignore_index=True)

In [192]:
# match by participant_label to add all columns from df_demographics to df
df = df.merge(df_demographics, left_on='participant.label', right_on='Participant id', how='left')
df.shape

(7200, 105)

In [193]:
df.head()

,participant.id_in_session,participant.code,participant.label,participant._is_bot,participant._index_in_pages,participant._max_page_index,participant._current_app_name,participant._current_page_name,participant.time_started_utc,participant.visited,participant.mturk_worker_id,participant.mturk_assignment_id,participant.payoff,participant.associations,session.code,session.label,session.mturk_HITId,session.mturk_HITGroupId,session.comment,session.is_demo,session.config.prolific_no_consent_link,session.config.prolific_completion_link,session.config.recaptcha_site_key,session.config.name,session.config.recaptcha_secret_key,session.config.participation_fee,session.config.real_world_currency_per_point,_1_consent.1.player.id_in_group,_1_consent.1.player.role,_1_consent.1.player.payoff,_1_consent.1.player.consent,_1_consent.1.group.id_in_subsession,_1_consent.1.subsession.round_number,_2_main.1.player.id_in_group,_2_main.1.player.role,_2_main.1.player.payoff,_2_main.1.player.association1,_2_main.1.player.association2,_2_main.1.player.association3,_2_main.1.player.association4,_2_main.1.player.association5,_2_main.1.player.association1_timer,_2_main.1.player.association2_timer,_2_main.1.player.association3_timer,_2_main.1.player.association4_timer,_2_main.1.player.association5_timer,_2_main.1.group.id_in_subsession,_2_main.1.subsession.round_number,_2_main.1.subsession.prolific_completion_link,_2_main.1.subsession.prolific_no_consent_link,_3_exit_questions.1.player.id_in_group,_3_exit_questions.1.player.role,_3_exit_questions.1.player.payoff,_3_exit_questions.1.player.ai_trust,_3_exit_questions.1.player.ai_risk,_3_exit_questions.1.player.daily_ai_use,_3_exit_questions.1.player.ai_expertise,_3_exit_questions.1.player.ai_expertise_justification,_3_exit_questions.1.group.id_in_subsession,_3_exit_questions.1.subsession.round_number,_4_demographics.1.player.id_in_group,_4_demographics.1.player.role,_4_demographics.1.player.payoff,_4_demographics.1.player.age,_4_demographics.1.player.gender,_4_demographics.1.player.gender_self_describe,_4_demographics.1.player.illusion_response,_4_demographics.1.group.id_in_subsession,_4_demographics.1.subsession.round_number,_5_feedback.1.player.id_in_group,_5_feedback.1.player.role,_5_feedback.1.player.payoff,_5_feedback.1.player.include_data,_5_feedback.1.player.include_data_justification,_5_feedback.1.player.ai_use_survey,_5_feedback.1.player.ai_use_details,_5_feedback.1.player.feedback,_5_feedback.1.player.check,_5_feedback.1.player.prolific_id,_5_feedback.1.player.recaptcha_token,_5_feedback.1.player.recaptcha_score,_5_feedback.1.player.participant_metrics_json,_5_feedback.1.group.id_in_subsession,_5_feedback.1.subsession.round_number,part,Submission id,Participant id,Status,Custom study tncs accepted at,Started at,Completed at,Reviewed at,Archived at,Time taken,Completion code,Total approvals,Age,Sex,Ethnicity simplified,Country of birth,Country of residence,Nationality,Language,Student status,Employment status
0,1,fm7mn92q,63b6be87ead45e4fa772fbf5,0,16,16,_5_feedback,p13_thanks,2025-10-20 14:12:25.358031,1,NaN,NaN,0.0,"{'association1': 'fake', 'association2': 'mach...",o8x15s3t,NaN,NaN,NaN,NaN,0,https://app.prolific.com/submissions/complete?...,https://app.prolific.com/submissions/complete?...,6Lfx--MrAAAAAO7TIvOcC7Mbm0iTZykUY6zx4v0t,ai_fat_2025,6Lfx--MrAAAAAECmXjGWwC2UlbmtcxYOCWQKUWqp,0.0,1.0,1,NaN,0.0,1.0,1,1,1,NaN,0.0,fake,machine like,artificial,intelligent,NaN,2144,5307,4453,22971,0,1,1,https://app.prolific.com/submissions/complete?...,https://app.prolific.com/submissions/complete?...,1,NaN,0.0,7.0,7.0,4.0,4.0,I have used it but don't know the complete inn...,1,1,1,NaN,0.0,41.0,female,NaN,duck,1,1,1,NaN,0.0,yes,NaN,no,NaN,NaN,NaN,63b6be87ead45e4fa772fbf5,0cAFcWeA6nI_500kwwOvwMSFT2vceClfh1lxU0uaQ0YH8P...,0.9,"{""totals"":{""copy"":0,""paste"":0,""cut"":0,""context...",1,1,part_1,68f6434058f7c62866582e82,63b6be87ead45e4fa772fbf5,APPROVED,Not Applicable,2025-10-20T14:12:22.665000Z,2025-10-20T14:14:53.633000Z,2025-10-20T19:19:16.898000Z,2025-10-20T14:14:54.471144Z,151.0,C1BZPBSV,10684.0,41,Female,White,United States,United States,United States,English,No,Full-Time
1,2,j2nzzv4a,5d617ba9364f9a0019f1dac3,0,16,16,_5_feedback,p13_thanks,2025-10-20 14:12:42.791913,1,NaN,NaN,0.0,"{'association1': 'destructive', 'association2'...",o8x15s3t,NaN,NaN,NaN,NaN,0,https://app.prolific.com/submissions/complete?...,https://app.prolific.com/submissions/complete?...,6Lfx--MrAAAAAO7TIvOcC7Mbm0iTZykUY6zx4v0t,ai_fat_2025,6Lfx--MrAAAAAECmXjGWwC2UlbmtcxYOCWQKUWqp,0.0,1.0,2,NaN,0.0,1.0,1,1,2,NaN,0.0,destructive,bad for environment,slop,killing creativity,scam magnet,5799,3548,6856,2871,22543,1,1,https://app.prolific.com/submissions/complete?...,https://app.prolific.com/submissions/complete?...,2,NaN,0.0,1.0,1.0,2.0,6.0,"If we're talking about AI generally, then mini...",1,1,2,NaN,0.0,39.0,non_binary,NaN,duck,1,1,2,NaN,0.0,yes,NaN,no,NaN,NaN,NaN,5d617ba9364f9a0019f1dac3,0cAFcWeA7D_8jo_V5K5a5Y6EiuIvrZAMjzgNvvjDX9XOEW...,0.9,"{""totals"":{""copy"":0,""paste"":0,""cut"":0,""context...",1,1,part_1,68f6435216f9543802533adc,5d617ba9364f9a0019f1dac3,APPROVED,Not Applicable,2025-10-20T14:12:34.919000Z,2025-10-20T14:14:59.275000Z,2025-10-20T19:17:44.679000Z,2025-10-20T14:15:00.095139Z,145.0,C1BZPBSV,12950.0,39,Female,Asian,Japan,United States,United States,Japanese,No,DATA_EXPIRED
2,3,xt3vxa15,6777d289f3eaa43bfd9c878c,0,16,16,_5_feedback,p13_thanks,2025-10-20 14:12:43.247663,1,NaN,NaN,0.0,"{'association1': 'Risky', 'association2': 'Sma...",o8x15s3t,NaN,NaN,NaN,NaN,0,https://app.prolific.com/submissions/complete?...,https://app.prolific.com/submissions/complete?...,6Lfx--MrAAAAAO7TIvOcC7Mbm0iTZykUY6zx4v0t,ai_fat_2025,6Lfx--MrAAAAAECmXjGWwC2UlbmtcxYOCWQKUWqp,0.0,1.0,3,NaN,0.0,1.0,1,1,3,NaN,0.0,Risky,Smart,Innovative,Data,Bad for environment,14179,5855,4881,6448,10896,1,1,https://app.prolific.com/submissions/complete?...,https://app.prolific.com/submissions/complete?...,3,NaN,0.0,3.0,0.0,2.0,1.0,I’ve used it a couple times. I have very gener...,1,1,3,NaN,0.0,33.0,male,NaN,Duck,1,1,3,NaN,0.0,yes,NaN,no,NaN,Thanks for the opportunity,NaN,6777d289f3eaa43bfd9c878c,0cAFcWeA6socJGwPFbHC0lv9qKveIZ476aH_GV_bZQl365...,0.9,"{""totals"":{""copy"":0,""paste"":0,""cut"":0,""context...",1,1,part_1,68f6435374d3dcbff86672c4,6777d289f3eaa43bfd9c878c,APPROVED,Not Applicable,2025-10-20T14:12:40.389000Z,2025-10-20T14:17:42.540000Z,2025-10-20T19:18:34.381000Z,2025-10-20T14:17:43.336095Z,303.0,C1BZPBSV,2986.0,33,Male,White,United States,United States,United States,English,No,Unemployed (and job seeking)
3,4,fevvwiqs,67d5d7068c0132f8de37783d,0,16,16,_5_feedback,p13_thanks,2025-10-20 14:13:01.139419,1,NaN,NaN,0.0,"{'association1': 'Smart technology', 'associat...",o8x15s3t,NaN,NaN,NaN,NaN,0,https://app.prolific.com/submissions/complete?...,https://app.prolific.com/submissions/complete?...,6Lfx--MrAAAAAO7TIvOcC7Mbm0iTZykUY6zx4v0t,ai_fat_2025,6Lfx--MrAAAAAECmXjGWwC2UlbmtcxYOCWQKUWqp,0.0,1.0,4,NaN,0.0,1.0,1,1,4,NaN,0.0,Smart technology,Job automation,Chatbots and assistants,Data analysis,Future innovation,34841,4419,4738,5001,14970,1,1,https://app.prolific.com/submissions/complete?...,https://app.prolific.com/submissions/complete?...,4,NaN,0.0,6.0,5.0,7.0,6.0,I have a solid understanding of how AI works a...,1,1,4,NaN,0.0,54.0,male,NaN,duck,1,1,4,NaN,0.0,yes,NaN,no,NaN,The survey was clear and easy to follow.,NaN,67d5d7068c0132f8de37783d,0cAFcWeA7ZOsdIReKRSowZZvbo1o2E7TwdFE6Auz-XWP6E...,0.9,"{""totals"":{""copy"":1,""paste"":0,""cut"":0,""context...",1,1,part_1,68f6435ce5eea13fb73f9d03,67d5d7068c0132f8de37783d,APPROVED,Not Applicable,2025-10-20T14:12:56.897000Z,2025-10-20T14:23:55.984000Z,2025-10-20T19:19:34.077000Z,2025-10-20T14:23:57.313728Z,660.0,C1BZPBSV,2673.0,54,Male,White,United States,United States,United States,English,DATA_EXPIRED,DATA_EXPIRED
4,5,1b4yqaax,6646476ce43edfa9033b00d5,0,16,16,_5_feedback,p13_thanks,2025-10-20 14:13:22.719416,1,NaN,NaN,0.0,"{'association1': 'waste of water', 'associatio...",o8x15s3t,NaN,NaN,NaN,NaN,0,https://app.prolific.com/submissions/complete?...,https://app.prolific.com/submissions/complete?...,6Lfx--MrAAAAAO7TIvOcC7Mbm0iTZykUY6zx4v0t,ai_fat_2025,6Lfx--MrAAAAAECmXjGWwC2UlbmtcxYOCWQKUWqp,0.0,1.0,5,NaN,0.0,1.0,1,1,5,NaN,0.0,waste of water,Job replacement,Ecological damage,Billionaires getting richer,AI psychosis,9794,10143,5240,17208,5755,1,1,https://app.prolific.com/submissions/complete?...,https://app.prolific.com/submissions/complete?...,5,NaN,0.0,1.0,2.0,1.0,4.0,I have used AI once or twice but do not like i...,1,1,5,NaN,0.0,35.0,female,NaN,Duck,1,1,5,NaN,0.0,yes,NaN,no,NaN,No,NaN,6646476ce43edfa9033b00d5,0cAFcWeA74k44l8-2tlXBzcNeKLFvm1P5Nsy5QceXiYCL4...,0.9,"{""totals"":{""copy"":0,""paste"":0,""cut"":0,""context...",1,1,part_1,68f643794fb9b140fa193e63,6646476ce43edfa9033b00d5,APPROVED,Not Applicable,2025-10-20T14:13:17.946000Z,2025-10-20T14:16:12.648000Z,2025-10-20T19:19:17.409000Z,2025-10-20T14:16:28.094149Z,175.0,C1BZPBSV,896.0,35,Female,White,United States,United States,United States,English,No,Full-Time

In [194]:
# drop rows where partcipant._current_page_name is not 'p13_thanks'
df = df[df['participant._current_page_name'] == 'p13_thanks']

In [195]:
for col in df.columns:
    print(col)

participant.id_in_session
participant.code
participant.label
participant._is_bot
participant._index_in_pages
participant._max_page_index
participant._current_app_name
participant._current_page_name
participant.time_started_utc
participant.visited
participant.mturk_worker_id
participant.mturk_assignment_id
participant.payoff
participant.associations
session.code
session.label
session.mturk_HITId
session.mturk_HITGroupId
session.comment
session.is_demo
session.config.prolific_no_consent_link
session.config.prolific_completion_link
session.config.recaptcha_site_key
session.config.name
session.config.recaptcha_secret_key
session.config.participation_fee
session.config.real_world_currency_per_point
_1_consent.1.player.id_in_group
_1_consent.1.player.role
_1_consent.1.player.payoff
_1_consent.1.player.consent
_1_consent.1.group.id_in_subsession
_1_consent.1.subsession.round_number
_2_main.1.player.id_in_group
_2_main.1.player.role
_2_main.1.player.payoff
_2_main.1.player.association1
_2_main.1.player.association2
_2_main.1.player.association3
_2_main.1.player.association4
_2_main.1.player.association5
_2_main.1.player.association1_timer
_2_main.1.player.association2_timer
_2_main.1.player.association3_timer
_2_main.1.player.association4_timer
_2_main.1.player.association5_timer
_2_main.1.group.id_in_subsession
_2_main.1.subsession.round_number
_2_main.1.subsession.prolific_completion_link
_2_main.1.subsession.prolific_no_consent_link
_3_exit_questions.1.player.id_in_group
_3_exit_questions.1.player.role
_3_exit_questions.1.player.payoff
_3_exit_questions.1.player.ai_trust
_3_exit_questions.1.player.ai_risk
_3_exit_questions.1.player.daily_ai_use
_3_exit_questions.1.player.ai_expertise
_3_exit_questions.1.player.ai_expertise_justification
_3_exit_questions.1.group.id_in_subsession
_3_exit_questions.1.subsession.round_number
_4_demographics.1.player.id_in_group
_4_demographics.1.player.role
_4_demographics.1.player.payoff
_4_demographics.1.player.age
_4_demographics.1.player.gender
_4_demographics.1.player.gender_self_describe
_4_demographics.1.player.illusion_response
_4_demographics.1.group.id_in_subsession
_4_demographics.1.subsession.round_number
_5_feedback.1.player.id_in_group
_5_feedback.1.player.role
_5_feedback.1.player.payoff
_5_feedback.1.player.include_data
_5_feedback.1.player.include_data_justification
_5_feedback.1.player.ai_use_survey
_5_feedback.1.player.ai_use_details
_5_feedback.1.player.feedback
_5_feedback.1.player.check
_5_feedback.1.player.prolific_id
_5_feedback.1.player.recaptcha_token
_5_feedback.1.player.recaptcha_score
_5_feedback.1.player.participant_metrics_json
_5_feedback.1.group.id_in_subsession
_5_feedback.1.subsession.round_number
part
Submission id
Participant id
Status
Custom study tncs accepted at
Started at
Completed at
Reviewed at
Archived at
Time taken
Completion code
Total approvals
Age
Sex
Ethnicity simplified
Country of birth
Country of residence
Nationality
Language
Student status
Employment status

In [196]:
# remove columns that are not needed
cols_to_remove = ['participant.id_in_session','participant._is_bot', 'participant._index_in_pages',
       'participant._max_page_index', 'participant._current_app_name','participant.visited', 'participant.mturk_worker_id',
       'participant.mturk_assignment_id', 'participant.payoff', 'session.code', 'session.label',
       'session.mturk_HITId', 'session.mturk_HITGroupId', 'session.comment',
       'session.is_demo', 'session.config.real_world_currency_per_point',
       'session.config.prolific_completion_link',
       'session.config.recaptcha_site_key',
       'session.config.prolific_no_consent_link', 'session.config.name',
       'session.config.recaptcha_secret_key',
       'session.config.participation_fee', '_1_consent.1.player.id_in_group',
       '_1_consent.1.player.role', '_1_consent.1.player.payoff', '_1_consent.1.group.id_in_subsession',
       '_1_consent.1.subsession.round_number', '_2_main.1.player.id_in_group',
       '_2_main.1.player.role', '_2_main.1.player.payoff', '_2_main.1.group.id_in_subsession',
       '_2_main.1.subsession.round_number',
       '_2_main.1.subsession.prolific_completion_link',
       '_2_main.1.subsession.prolific_no_consent_link',
       '_3_exit_questions.1.player.id_in_group',
       '_3_exit_questions.1.player.role', '_3_exit_questions.1.player.payoff', '_3_exit_questions.1.group.id_in_subsession',
       '_3_exit_questions.1.subsession.round_number',
       '_4_demographics.1.player.id_in_group', '_4_demographics.1.player.role',
       '_4_demographics.1.player.payoff', '_4_demographics.1.group.id_in_subsession',
       '_4_demographics.1.subsession.round_number',
       '_5_feedback.1.player.id_in_group', '_5_feedback.1.player.role',
       '_5_feedback.1.player.payoff', '_5_feedback.1.player.recaptcha_token', '_5_feedback.1.group.id_in_subsession',
       '_5_feedback.1.subsession.round_number',
       'Participant id', 'Submission id', 'Custom study tncs accepted at',
       'Completion code', 'Archived at', 'Started at', 'Completed at',
       'Reviewed at', 'Status', 'Nationality', 'Language', 'participant.label']
df = df.drop(columns=cols_to_remove)

In [197]:
# rename columns to keep only last part after last dot
df.columns = [col.split('.')[-1] for col in df.columns]

In [198]:
df.columns

Index(['code', '_current_page_name', 'time_started_utc', 'associations',
       'consent', 'association1', 'association2', 'association3',
       'association4', 'association5', 'association1_timer',
       'association2_timer', 'association3_timer', 'association4_timer',
       'association5_timer', 'ai_trust', 'ai_risk', 'daily_ai_use',
       'ai_expertise', 'ai_expertise_justification', 'age', 'gender',
       'gender_self_describe', 'illusion_response', 'include_data',
       'include_data_justification', 'ai_use_survey', 'ai_use_details',
       'feedback', 'check', 'prolific_id', 'recaptcha_score',
       'participant_metrics_json', 'part', 'Time taken', 'Total approvals',
       'Age', 'Sex', 'Ethnicity simplified', 'Country of birth',
       'Country of residence', 'Student status', 'Employment status'],
      dtype='object')

In [199]:
# rename vars
df = df.rename(columns={'check': 'honeypot_checkbox'})
df = df.rename(columns={'Age': 'age_prolific'})
df = df.rename(columns={'Ethnicity simplified': 'ethnicity'})
df = df.rename(columns={'Gender': 'gender'})
df = df.rename(columns={'Country of birth': 'country_birth'})
df = df.rename(columns={'Country of residence': 'country'})
df = df.rename(columns={'Student status': 'student'})
df = df.rename(columns={'Employment status': 'employment'})

In [200]:
for i in range(1, 6):
    df[f'association{i}_lower'] = df[f'association{i}'].str.lower()

In [201]:
df.head()

,code,_current_page_name,time_started_utc,associations,consent,association1,association2,association3,association4,association5,association1_timer,association2_timer,association3_timer,association4_timer,association5_timer,ai_trust,ai_risk,daily_ai_use,ai_expertise,ai_expertise_justification,age,gender,gender_self_describe,illusion_response,include_data,include_data_justification,ai_use_survey,ai_use_details,feedback,honeypot_checkbox,prolific_id,recaptcha_score,participant_metrics_json,part,Time taken,Total approvals,age_prolific,Sex,ethnicity,country_birth,country,student,employment,association1_lower,association2_lower,association3_lower,association4_lower,association5_lower
0,fm7mn92q,p13_thanks,2025-10-20 14:12:25.358031,"{'association1': 'fake', 'association2': 'mach...",1.0,fake,machine like,artificial,intelligent,NaN,2144,5307,4453,22971,0,7.0,7.0,4.0,4.0,I have used it but don't know the complete inn...,41.0,female,NaN,duck,yes,NaN,no,NaN,NaN,NaN,63b6be87ead45e4fa772fbf5,0.9,"{""totals"":{""copy"":0,""paste"":0,""cut"":0,""context...",part_1,151.0,10684.0,41,Female,White,United States,United States,No,Full-Time,fake,machine like,artificial,intelligent,NaN
1,j2nzzv4a,p13_thanks,2025-10-20 14:12:42.791913,"{'association1': 'destructive', 'association2'...",1.0,destructive,bad for environment,slop,killing creativity,scam magnet,5799,3548,6856,2871,22543,1.0,1.0,2.0,6.0,"If we're talking about AI generally, then mini...",39.0,non_binary,NaN,duck,yes,NaN,no,NaN,NaN,NaN,5d617ba9364f9a0019f1dac3,0.9,"{""totals"":{""copy"":0,""paste"":0,""cut"":0,""context...",part_1,145.0,12950.0,39,Female,Asian,Japan,United States,No,DATA_EXPIRED,destructive,bad for environment,slop,killing creativity,scam magnet
2,xt3vxa15,p13_thanks,2025-10-20 14:12:43.247663,"{'association1': 'Risky', 'association2': 'Sma...",1.0,Risky,Smart,Innovative,Data,Bad for environment,14179,5855,4881,6448,10896,3.0,0.0,2.0,1.0,I’ve used it a couple times. I have very gener...,33.0,male,NaN,Duck,yes,NaN,no,NaN,Thanks for the opportunity,NaN,6777d289f3eaa43bfd9c878c,0.9,"{""totals"":{""copy"":0,""paste"":0,""cut"":0,""context...",part_1,303.0,2986.0,33,Male,White,United States,United States,No,Unemployed (and job seeking),risky,smart,innovative,data,bad for environment
3,fevvwiqs,p13_thanks,2025-10-20 14:13:01.139419,"{'association1': 'Smart technology', 'associat...",1.0,Smart technology,Job automation,Chatbots and assistants,Data analysis,Future innovation,34841,4419,4738,5001,14970,6.0,5.0,7.0,6.0,I have a solid understanding of how AI works a...,54.0,male,NaN,duck,yes,NaN,no,NaN,The survey was clear and easy to follow.,NaN,67d5d7068c0132f8de37783d,0.9,"{""totals"":{""copy"":1,""paste"":0,""cut"":0,""context...",part_1,660.0,2673.0,54,Male,White,United States,United States,DATA_EXPIRED,DATA_EXPIRED,smart technology,job automation,chatbots and assistants,data analysis,future innovation
4,1b4yqaax,p13_thanks,2025-10-20 14:13:22.719416,"{'association1': 'waste of water', 'associatio...",1.0,waste of water,Job replacement,Ecological damage,Billionaires getting richer,AI psychosis,9794,10143,5240,17208,5755,1.0,2.0,1.0,4.0,I have used AI once or twice but do not like i...,35.0,female,NaN,Duck,yes,NaN,no,NaN,No,NaN,6646476ce43edfa9033b00d5,0.9,"{""totals"":{""copy"":0,""paste"":0,""cut"":0,""context...",part_1,175.0,896.0,35,Female,White,United States,United States,No,Full-Time,waste of water,job replacement,ecological damage,billionaires getting richer,ai psychosis

In [202]:
df['_current_page_name'].value_counts()

_current_page_name
p13_thanks    3242
Name: count, dtype: int64

In [203]:
# rename _current_page_name to finished and set all values to True
df = df.rename(columns={'_current_page_name': 'finished'})
df['finished'] = True

In [204]:
df.shape

(3242, 48)

In [205]:
# save to new csv
df.to_csv('./data/clean/ai_fat_wave3.csv', index=False)

In [206]:
all_cols = df.columns.tolist()
stub_cols = [f'association{i}' for i in range(1, 6)]
timer_cols = [f'association{i}_timer' for i in range(1, 6)]

other_cols = [col for col in all_cols if col not in stub_cols and col not in timer_cols]

df_long = pd.wide_to_long(
    df,
    stubnames=['association', 'association_timer'],
    i=other_cols,                              
    j='association_number'                    
).reset_index()

df_long['association'] = df_long['association']
df_long['association_lower'] = df_long['association'].str.lower()

In [207]:
timer_col_index = df_long.columns.get_loc('association_timer')
df_long.insert(
    timer_col_index, 
    'association_lower', 
    df_long.pop('association_lower')
)

df_long = df_long.drop(columns=['association_number'])

In [208]:
df_long.to_csv('./data/clean/ai_fat_wave3_long.csv', index=False)